### ISSUE TITLE
關於第六章有些地方不太懂

### ISSUE THREAD

**Issue by agda5566** [emacs-tw/emacs-101#10]
```lisp
;; package.el 相關設定
(require 'package)
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)
```

第3行的網址是不是要改成`https://melpa.org/packages/`
這一段是放在init.el還是自己在,emacs.d目錄下創一個package.el檔？
我嘗試創package.el檔，但似乎沒甚麼作用，我放到init.el檔才有出來
如果要放在package.el檔，init.el那邊要先設定載入package.el嗎？

我嘗試(add-to-list 'load-path "~/.emacs.d/package.el") 但打開emacs跳出錯誤

另外我放到init的時候，有嘗試下載一些套件比如auto-complete
接著我重開嘗試寫c都沒有自動補全
是否也需要在init手動載入它呢？ 
比如
(add-to-list 'load-path "~/.emacs.d/elpa/auto-complete") 
(require 'auto-complete)  
抱歉問題有點多......大大願意就回答，不過我會持續尋找答案的

**Comment by kuanyui** [comment]
> 第3行的網址是不是要改成https://melpa.org/packages/

他們改了嗎？以MELPA官方的README為準。

> 這一段是放在init.el還是自己在,emacs.d目錄下創一個package.el檔？

前者

> 我嘗試創package.el檔，但似乎沒甚麼作用，我放到init.el檔才有出來
> 如果要放在package.el檔，init.el那邊要先設定載入package.el嗎？
1. 不要這樣作，`package.el` 跟內建的package.el名稱相衝。
2. 如果真要作就改成`rc-package.el`，總之就是不要同名。請參考 @kanru 或 @kuanyui 的設定檔架構。
3. 請告訴我是哪一段敘述會讓你會錯意理解成這樣，我會再修飾一下。

> 我嘗試(add-to-list 'load-path "~/.emacs.d/package.el") 但打開emacs跳出錯誤

`load-path` 裡面塞的是目錄而不是檔案。

> 另外我放到init的時候，有嘗試下載一些套件比如auto-complete

題外話，auto-complete在console下很廢物，現在比較推薦改用company了。

> 接著我重開嘗試寫c都沒有自動補全

你確定有打開 auto-complete？M-x auto-complete-mode

其他的自己去想辦法Google，我沒有在寫C，C++我自己也都是用QtCreator在寫。

順帶一提， company跟auto-complete都只是completion framework，裡面本身不包含各個語言的補全，要自己另外裝。例如ac-XXX.el，company-XXX.el

> 是否也需要在init手動載入它呢？
> 比如
> (add-to-list 'load-path "~/.emacs.d/elpa/auto-complete")
> (require 'auto-complete)
> 抱歉問題有點多......大大願意就回答，不過我會持續尋找答案的
1. 透過package.el安裝的東西不用手動add-to-list，他自己會幫你做好。
2. 請告訴我是哪段敘述會讓你會錯意？謝謝。

**Comment by coldnew** [comment]
在你的 init.el 開頭，加上以下設定  (原文章可能有錯，呼叫 @kuanyui )

``` elisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/")))
  ;; This must come before configurations of installed packages.
  ;; Don't delete this line. If you don't want it, just comment it out by adding a
  ;; semicolon to the start of the line. You may delete these explanatory
  ;; comments.
  (package-initialize)
```

若你看得懂英文的話，可以參考 melpa 的說明: https://github.com/melpa/melpa

其他見上一篇文章......    (打一半去開會然後樓上就出現了 XD)

**Comment by agda5566** [comment]
> 他們改了嗎？以MELPA官方的README為準。

我看他的guide頁面寫好像改了  [melpa](https://melpa.org/#/getting-started) （還是我會錯意......）

> 不要這樣作，package.el 跟內建的package.el名稱相衝。
> 如果真要作就改成rc-package.el，總之就是不要同名。請參考 @kanru 或 @kuanyui 的設定檔架構。
> 請告訴我是哪一段敘述會讓你會錯意理解成這樣，我會再修飾一下。

阿原來是這樣阿，主要是我自己在.emacs.d目錄下找了很久都找不到所謂的package.el，於是我就猜測「阿！是不是也要像init.el自己創了」，結果不能用xD，我也猜想是不是package.el根本看不到？感謝大大解惑

> 你確定有打開 auto-complete？M-x auto-complete-mode
> 其他的自己去想辦法Google，我沒有在寫C，C++我自己也都是用QtCreator在寫。
> 順帶一提， company跟auto-complete都只是completion framework，裡面本身不包含各個語言的補全，要自己另外裝。例如ac-XXX.el，company-XXX.el

後來去那個套件的用戶手冊發現M-x auto-complete-mode，嘗試之後可以打開

> 透過package.el安裝的東西不用手動add-to-list，他自己會幫你做好。
> 請告訴我是哪段敘述會讓你會錯意？謝謝。

可能我自己太愛腦補，覺得高手講話是講一半，要讓別人自行體悟xD
也許加個p.s.你在.emacs.d目錄下看不到package.el是正常的，也請不要自行創建
如要創建請使用別的名字，就像大大說的那樣rc-package.el

**Comment by agda5566** [comment]
>   (require 'package)
>   (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
>   (when (< emacs-major-version 24)
>   ;; For important compatibility libraries like cl-lib
>   (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/")))
>   ;; This must come before configurations of installed packages.
>   ;; Don't delete this line. If you don't want it, just comment it out by adding a
>   ;; semicolon to the start of the line. You may delete these explanatory
>   ;; comments.
>   (package-initialize)
> 
> > 若你看得懂英文的話，可以參考 melpa 的說明: https://github.com/melpa/melpa
> > 其他見上一篇文章...... (打一半去開會然後樓上就出現了 XD)

感謝大大
[http://melpa.milkbox.net/packages/](http://melpa.milkbox.net/packages/)
似乎好像還是能用？看你們的樣子似乎emacs使用上還是沒問題

**Comment by coldnew** [comment]
emacs-lisp 沒有 namespace, 因此包含設定檔的名稱都要注意。

舉例來說，你的設定檔案有 `packages.el`，會有機會蓋掉系統得 `packages.el` ，因此個人的設定檔案都建議加上 prefix, ex: `packages.el` -> `my-packages.el` 。

**Comment by kuanyui** [comment]
@coldnew 恭請大大push <(_ _)>

**Comment by agda5566** [comment]
> emacs-lisp 沒有 namespace, 因此包含設定檔的名稱都要注意。
> 舉例來說，你的設定檔案有 packages.el，會有機會蓋掉系統得 packages.el ，因此個人的設定檔案都建議加上 prefix, ex: packages.el -> my-packages.el 。

恩恩，謝謝 大大，現在懂惹^—^

**Comment by wildskyf** [comment]
他們改了沒錯哦
https://github.com/melpa/melpa/blob/master/README.md#usage

**Comment by wildskyf** [comment]
赫然發現我也只裝了 conpany 而已，難怪啥自動補齊都沒有ＸＤＤ

**Comment by bcbcarl** [comment]
這 issue 算解決了嗎？

**Comment by wildskyf** [comment]
先關吧，原 po 有問題再 reopen

2016年11月11日 17:57，"Carl X. Su" notifications@github.com寫道：
