### ISSUE TITLE
English version or similar project?

### ISSUE THREAD

**Issue by jononomo** [emacs-tw/emacs-101#15]
这个项目看起来很有趣。有英语版本或类似资源吗？

非常感谢。

---

This project looks very interesting to me.  Is there a version, or a similar resource, in English?

Thanks very much.

**Comment by kuanyui** [comment]
我不知道，這本教學是照我自己使用Emacs的經驗寫的，當時並沒有想太多就直接用中文寫，也沒有參照特定一本書籍或教學（所以我還蠻自信這本應該沒有落入舊有窠臼）。

如果想要翻譯成英文也歡迎，看要丟PR或者直接fork出去都可以，我的工作比較沒時間去搞這個了。

I don't know. This tutorial is totally from my own using experience on Emacs. For a personal project, I didn't consider to write this in English. And it isn't based on any specific book or tutorial.

It's surely welcome to translate this work to English, PR or fork are ok. I have had not so much time and passion to do this.

**Comment by jononomo** [comment]
謝謝

---

Thank you.
