### ISSUE TITLE
关于 Vim、ST、Emacs、Atom 的体量

### ISSUE THREAD

**Issue by louy2** [emacs-tw/emacs-101#2]
比较 Windows 下各编辑器的安装包大小
- Vim 64位 [Bintray](https://bintray.com/veegee/generic/vim_x64#files/)：6.1MB
- ST3 Beta 64位 [Official](http://www.sublimetext.com/3)：7.7MB
- Emacs 64位 [Sourceforge](http://sourceforge.net/projects/emacsbinw64/files/snapshot/)：50.1MB
- Atom 64位 [Github](https://github.com/atom/atom/releases)：85.8MB

基本上和可定制性成正比。

**Comment by kuanyui** [comment]
這個說法有點奇怪啊....@@

**Comment by louy2** [comment]
是針對 [01-你應該會想知道的Emacs Q & A.org](https://github.com/emacs-tw/emacs-101/blob/master/01-%E4%BD%A0%E6%87%89%E8%A9%B2%E6%9C%83%E6%83%B3%E7%9F%A5%E9%81%93%E7%9A%84Emacs%20Q%20%26%20A.org) 里缺點的第 3 條。 Sublime Text 是很輕量的，它連 UI Kit 都是作者自己寫的。

Atom 的可定制性高在於它除了是一個完整 JavaScript 解釋器，還是一個網頁瀏覽器，因此在 UI 上靈活性僅次於拿 WPF 寫原生 UI。有人拿 ClojureScript （基於 JavaScript 的 Lisp 方言）和 Atom 搭，感想是「簡直 Emacs 重生」。

**Comment by kuanyui** [comment]
原來如此。
